# trying with ghc 9.2
resolver: lts-20.26
# resolver: lts-18.28
# resolver: lts-16.31 # ghc 8.8, fails with glibc issue

packages:
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test
- third_party/snappy

extra-deps:
- c2hs-0.28.8
- language-c-0.9.2
- snappy-framing-0.1.2
# - snappy-0.2.0.2

# - proto-lens-0.7.1.3
# - proto-lens-protobuf-types-0.7.1.2
# - proto-lens-runtime-0.7.0.4
# - proto-lens-setup-0.4.0.6
# - proto-lens-protoc-0.7.1.1
  
# - proto-lens-0.7.1.4
# - proto-lens-protobuf-types-0.7.2.0@sha256:78f9d686aca30f1b569145b6c0d7a20f8398b5f5de601ec1c3d07ac644ea1e66,3814
# - proto-lens-runtime-0.7.0.5@sha256:97a552648d3ca064a3e8a147244ffc589ccd30bd845f13e88271654924534b28,3051
# - proto-lens-setup-0.4.0.7@sha256:acca0b04e033ea0a017f809d91a7dbc942e025ec6bc275fa21647352722c74cc,3122
# - proto-lens-protoc-0.8.0.0

# - proto-lens-0.7.0.0
# - proto-lens-protobuf-types-0.7.0.0
# - proto-lens-runtime-0.7.0.0
# - proto-lens-setup-0.4.0.4
# - proto-lens-protoc-0.7.0.0
# - profunctors-5.5.2
#
# For Mac OS X, whose linker doesn't use this path by default
# unless you run `xcode-select --install`.
# TODO: remove this once we stop depending on `snappy`.
extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include

docker:
    enable: false
    image: tensorflow/haskell:2.13.0

nix:
    enable: false
    # trying with nixos-23.11 with libtensorflow 2.13.0
    path: ["nixpkgs=https://github.com/NixOS/nixpkgs/archive/219951b495fc2eac67b1456824cc1ec1fd2ee659.tar.gz"]
    packages: [snappy, zlib, protobuf, libtensorflow]
