resolver: lts-20.26

packages:
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test
- snappy

extra-deps:
- c2hs-0.28.8
- language-c-0.9.2
- snappy-framing-0.1.2

# For Mac OS X, whose linker doesn't use this path by default
# unless you run `xcode-select --install`.
# TODO: remove this once we stop depending on `snappy`.
extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include

docker:
    enable: false
    image: tensorflow/haskell:2.13.0

nix:
    enable: false
    # trying with nixos-23.11 with libtensorflow 2.13.0
    path: ["nixpkgs=https://github.com/NixOS/nixpkgs/archive/219951b495fc2eac67b1456824cc1ec1fd2ee659.tar.gz"]
    packages: [snappy, zlib, protobuf, libtensorflow]
